/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gojek.ristek;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void additionTest() {
        App classUnderTest = new App();
        assertEquals(7, classUnderTest.addition(2, 5));
    }

    @Test
    void subtractionTest() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.subtration(5, 2));
    }
}
